cora:
  lr: 0.001
  lr_f: 0.01
  num_hidden: 512
  num_heads: 4
  num_layers: 2
  weight_decay: 1e-5
  weight_decay_f: 1e-4
  max_epoch: 1500
  max_epoch_f: 300
  encoder: gcn
  activation: relu
  in_drop: 0.6
  attn_drop: 0.1
  linear_prob: True
  optimizer: adam
  scheduler: False
  num_proj_hidden: 512
  drop_edge_rate_1: 0.5
  drop_edge_rate_2: 0.5
  drop_feature_rate_1: 0.5
  drop_feature_rate_2: 0.5
  tau: 0.4
citeseer:
  lr: 0.001
  lr_f: 0.01
  num_hidden: 512
  num_heads: 2
  num_layers: 2
  weight_decay: 1e-5
  weight_decay_f: 0.01
  max_epoch: 1500
  max_epoch_f: 300
  encoder: gat
  activation: prelu
  in_drop: 0.6
  attn_drop: 0.1
  linear_prob: True
  optimizer: adam
  scheduler: False
  num_proj_hidden: 512
  drop_edge_rate_1: 0.5
  drop_edge_rate_2: 0.5
  drop_feature_rate_1: 0.5
  drop_feature_rate_2: 0.5
  tau: 0.9
pubmed:
  lr: 0.001
  lr_f: 0.01
  num_hidden: 1024
  num_heads: 4
  num_layers: 2
  weight_decay: 1e-5
  weight_decay_f: 1e-4
  max_epoch: 1200
  max_epoch_f: 300
  encoder: gcn
  activation: relu
  in_drop: 0.5
  attn_drop: 0.1
  linear_prob: True
  optimizer: adam
  scheduler: False
  num_proj_hidden: 512
  drop_edge_rate_1: 0.4
  drop_edge_rate_2: 0.1
  drop_feature_rate_1: 0.0
  drop_feature_rate_2: 0.2
  tau: 0.7