cora:
  seeds: 0
  lr: 0.001
  num_hidden: 512
  num_proj_hidden: 512
  activation: 'relu'
  lr_f: 0.01
  max_epoch_f: 2000
  weight_decay_f: 1e-4
  num_layers: 2
  drop_edge_rate_1: 0.4
  drop_edge_rate_2: 0.4
  drop_feature_rate_1: 0.1
  drop_feature_rate_2: 0.1
  lambd: 0.001
  max_epoch: 50
  weight_decay: 0.0000
  scheduler: True
citeSeer:
  seeds: 0
  lr: 0.001
  num_hidden: 512
  num_proj_hidden: 512
  activation: 'prelu'
  lr_f: 0.01
  max_epoch_f: 2000
  weight_decay_f: 0.01
  num_layers: 2
  drop_edge_rate_1: 0.4
  drop_edge_rate_2: 0.4
  drop_feature_rate_1: 0
  drop_feature_rate_2: 0
  lambd: 0.0005
  max_epoch: 20
  weight_decay: 0.0000
  scheduler: True
pubmeds:
  seeds: 0
  lr: 0.001
  num_hidden: 512
  num_proj_hidden: 512
  activation: 'relu'
  lr_f: 0.01
  max_epoch_f: 2000
  weight_decay_f: 1e-4
  num_layers: 2
  drop_edge_rate_1: 0.4
  drop_edge_rate_2: 0.1
  drop_feature_rate_1: 0.3
  drop_feature_rate_2: 0.5
  lambd: 0.001
  max_epoch: 100
  weight_decay: 0.0000
  scheduler: True