cora:
  lr: 0.001
  lr_f: 0.01
  num_hidden: 512
  num_heads: 4
  num_layers: 2
  weight_decay: 2e-4
  weight_decay_f: 1e-4
  max_epoch: 1500
  max_epoch_f: 300
  mask_rate: 0.5
  encoder: gat
  decoder: gat
  activation: prelu
  in_drop: 0.2
  attn_drop: 0.1
  linear_prob: True
  loss_fn: sce
  drop_edge_rate: 0.0
  optimizer: adam
  replace_rate: 0.05
  alpha_l: 3
  scheduler: True
citeseer:
  lr: 0.001
  lr_f: 0.01
  num_hidden: 512
  num_heads: 2
  num_layers: 2
  weight_decay: 2e-5
  weight_decay_f: 0.01
  max_epoch: 300
  max_epoch_f: 300
  mask_rate: 0.5
  encoder: gat
  decoder: gat
  activation: prelu
  in_drop: 0.2
  attn_drop: 0.1
  linear_prob: True
  loss_fn: sce
  drop_edge_rate: 0.0
  optimizer: adam
  replace_rate: 0.1
  alpha_l: 1 # or 3
  scheduler: True
pubmed:
  lr: 0.001
  lr_f: 0.01
  num_hidden: 1024
  num_heads: 4
  num_layers: 2
  weight_decay: 1e-5
  weight_decay_f: 1e-4
  max_epoch: 1000
  max_epoch_f: 300
  mask_rate: 0.75
  encoder: gat
  decoder: gat
  activation: prelu
  in_drop: 0.2
  attn_drop: 0.1
  linear_prob: True
  loss_fn: sce
  drop_edge_rate: 0.0
  optimizer: adam
  replace_rate: 0.0
  alpha_l: 3
  scheduler: True
ogbn-arxiv:
  lr: 0.001
  lr_f: 0.01
  num_hidden: 1024
  num_heads: 4
  weight_decay: 0
  weight_decay_f: 5e-4
  max_epoch: 60
  max_epoch_f: 1000
  mask_rate: 0.5
  drop_edge_rate: 0
  num_layers: 3
  encoder: gat
  decoder: gat
  activation: prelu
  in_drop: 0.2
  attn_drop: 0.1
  linear_prob: True
  loss_fn: sce
  replace_rate: 0.0
  alpha_l: 3 # 2
  scheduler: True
  num_out_heads: 1
  batch_size: 512
  batch_size_f: 256
  optimizer: adam
  residual: True
  norm: layernorm
ogbn-products:
  lr: 0.001
  lr_f: 0.01
  num_hidden: 1024
  num_heads: 4
  weight_decay: 0
  weight_decay_f: 5e-4
  max_epoch: 20
  max_epoch_f: 1000
  mask_rate: 0.5
  drop_edge_rate: 0
  num_layers: 3
  encoder: gat
  decoder: gat
  activation: prelu
  in_drop: 0.2
  attn_drop: 0.1
  linear_prob: True
  loss_fn: sce
  replace_rate: 0.0
  alpha_l: 3 # 2
  scheduler: True
  num_out_heads: 1
  batch_size: 512
  batch_size_f: 256
  optimizer: adam
  residual: True
  norm: layernorm
ogbn-papers100M:
  lr: 0.001
  lr_f: 0.01
  num_hidden: 1024
  num_heads: 4
  weight_decay: 0
  weight_decay_f: 5e-4
  max_epoch: 10
  max_epoch_f: 1000
  mask_rate: 0.5
  drop_edge_rate: 0
  num_layers: 3
  encoder: gat
  decoder: gat
  activation: prelu
  in_drop: 0.2
  attn_drop: 0.1
  linear_prob: True
  loss_fn: sce
  replace_rate: 0.0
  alpha_l: 3 # 2
  scheduler: True
  num_out_heads: 1
  batch_size: 512
  batch_size_f: 256
  optimizer: adam
  residual: True
  norm: layernorm
