cora:
  lr: 0.001
  lr_f: 0.025
  num_hidden: 1024
  num_heads: 8
  num_out_heads: 1
  num_layers: 2
  weight_decay: 2e-4
  weight_decay_f: 1e-4
  max_epoch: 2000
  max_epoch_f: 300
  mask_rate: 0.5
  encoder: gat
  decoder: gat
  activation: prelu
  attn_drop: 0.1
  linear_prob: True
  in_drop: 0.2
  loss_fn: sce
  drop_edge_rate: 0.0
  optimizer: adam
  replace_rate: 0.1
  alpha_l: 4
  scheduler: True
  remask_method: fixed
  momentum: 0
  lam: 0.1
citeseer:
  lr: 0.0005 # 0.0005
  lr_f: 0.025
  num_hidden: 1024
  num_heads: 4
  num_out_heads: 1
  num_layers: 2
  weight_decay: 1e-4
  weight_decay_f: 1e-2
  max_epoch: 500
  max_epoch_f: 500
  mask_rate: 0.5
  encoder: gat
  decoder: gat
  activation: prelu
  attn_drop: 0.1
  linear_prob: True
  in_drop: 0.2
  loss_fn: sce
  drop_edge_rate: 0.0
  optimizer: adam
  replace_rate: 0.0
  alpha_l: 1
  scheduler: True
  remask_method: fixed
  momentum: 1
  lam: 0.1
pubmed:
  lr: 0.005
  lr_f: 0.025
  num_hidden: 512
  num_heads: 2
  num_out_heads: 1
  num_layers: 2
  weight_decay: 1e-5
  weight_decay_f: 5e-4
  max_epoch: 2000
  max_epoch_f: 500
  mask_rate: 0.9
  encoder: gat
  decoder: gat
  activation: prelu
  attn_drop: 0.1
  linear_prob: True
  in_drop: 0.2
  loss_fn: sce
  drop_edge_rate: 0.0
  optimizer: adam
  replace_rate: 0.0
  alpha_l: 4
  scheduler: True
  remask_method: fixed
  momentum: 0.995
  lam: 1
ogbn-arxiv:
  lr: 0.0025
  lr_f: 0.005
  num_hidden: 1024
  num_heads: 8
  num_out_heads: 1
  weight_decay: 0.06
  weight_decay_f: 1e-4
  max_epoch: 60
  max_epoch_f: 1000
  batch_size: 512
  batch_size_f: 256
  mask_rate: 0.5
  num_layers: 4
  encoder: gat
  decoder: gat
  activation: prelu
  attn_drop: 0.1
  linear_prob: True
  in_drop: 0.2
  loss_fn: sce
  drop_edge_rate: 0.5
  optimizer: adam
  alpha_l: 6
  scheduler: True
  remask_method: random
  momentum: 0.996
  lam: 10.0
  delayed_ema_epoch: 40
  num_remasking: 3
ogbn-papers100M:
  lr: 0.001
  lr_f: 0.001
  num_hidden: 1024
  num_heads: 4
  num_out_heads: 1
  num_layers: 4
  weight_decay: 0.05
  weight_decay_f: 0
  max_epoch: 10
  max_epoch_f: 1000
  batch_size: 512
  batch_size_f: 256
  mask_rate: 0.5
  encoder: gat
  decoder: gat
  activation: prelu
  attn_drop: 0.2
  linear_prob: True
  in_drop: 0.2
  loss_fn: sce
  drop_edge_rate: 0.5
  optimizer: adam
  alpha_l: 2
  scheduler: True
  remask_method: random
  momentum: 0.996
  lam: 10.0
  delayed_ema_epoch: 0
  num_remasking: 3
ogbn-products:
  lr: 0.002
  lr_f: 0.001
  num_hidden: 1024
  num_heads: 4
  num_out_heads: 1
  num_layers: 4
  weight_decay: 0.04
  weight_decay_f: 0
  max_epoch: 20
  max_epoch_f: 1000
  batch_size: 512
  batch_size_f: 256
  mask_rate: 0.5
  encoder: gat
  decoder: gat
  activation: prelu
  attn_drop: 0.2
  linear_prob: True
  in_drop: 0.2
  loss_fn: sce
  drop_edge_rate: 0.5
  optimizer: adam
  alpha_l: 3
  scheduler: True
  remask_method: random
  momentum: 0.996
  lam: 5.0
  delayed_ema_epoch: 0
  num_remasking: 3