cora:
  lr: 0.001
  max_epoch_f: 2000
  weight_decay_f: 1e-4
  num_layers: 2
  drop_edge_rate_1: 0.4
  drop_edge_rate_2: 0.4
  drop_feature_rate_1: 0.1
  drop_feature_rate_2: 0.1
  max_epoch: 50
  scheduler: True
citeSeer:
  lr: 0.001
  max_epoch_f: 2000
  weight_decay_f: 1e-4
  num_layers: 2
  drop_edge_rate_1: 0.4
  drop_edge_rate_2: 0.4
  drop_feature_rate_1: 0.1
  drop_feature_rate_2: 0.1
  max_epoch: 50
  scheduler: True
pubmeds:
  lr: 0.001
  max_epoch_f: 2000
  weight_decay_f: 1e-4
  num_layers: 2
  drop_edge_rate_1: 0.4
  drop_edge_rate_2: 0.4
  drop_feature_rate_1: 0.1
  drop_feature_rate_2: 0.1
  max_epoch: 50
  scheduler: True