cora:
  seeds: 39788
  lr: 0.0005
  num_hidden: 128
  num_proj_hidden: 128
  activation: 'relu'
  lr_f: 0.01
  max_epoch_f: 300
  weight_decay_f: 1e-4
  num_layers: 2
  drop_edge_rate_1: 0.2
  drop_edge_rate_2: 0.4
  drop_feature_rate_1: 0.3
  drop_feature_rate_2: 0.4
  tau: 0.4
  max_epoch: 300
  weight_decay: 0.00001
  scheduler: True
citeSeer:
  seeds: 38108
  learning_rate: 0.001
  num_hidden: 256
  num_proj_hidden: 256
  activation: 'prelu'
  lr_f: 0.01
  max_epoch_f: 300
  weight_decay_f: 0.01
  num_layers: 2
  drop_edge_rate_1: 0.2
  drop_edge_rate_2: 0.0
  drop_feature_rate_1: 0.3
  drop_feature_rate_2: 0.2
  tau: 0.9
  max_epoch: 200
  weight_decay: 0.00001
  scheduler: True
pubmeds:
  seeds: 23344
  learning_rate: 0.001
  num_hidden: 256
  num_proj_hidden: 256
  activation: 'relu'
  lr_f: 0.01
  max_epoch_f: 300
  weight_decay_f: 1e-4
  num_layers: 2
  drop_edge_rate_1: 0.4
  drop_edge_rate_2: 0.1
  drop_feature_rate_1: 0.0
  drop_feature_rate_2: 0.2
  tau: 0.7
  max_epoch: 1500
  weight_decay: 0.00001
  scheduler: True