cora:
  lr: 0.001
  lr_f: 0.01
  num_hidden: 512
  num_heads: 4
  num_layers: 2
  weight_decay: 1e-4
  weight_decay_f: 1e-4
  max_epoch: 1500
  max_epoch_f: 300
  encoder: gat
  activation: prelu
  in_drop: 0.4
  attn_drop: 0.1
  linear_prob: True
  optimizer: adam
  scheduler: True
  pred_hid: 512
  drop_edge_rate_1: 0.5
  drop_edge_rate_2: 0.5
  drop_feature_rate_1: 0.5
  drop_feature_rate_2: 0.5
citeseer:
  lr: 0.001
  lr_f: 0.01
  num_hidden: 512
  num_heads: 2
  num_layers: 2
  weight_decay: 1e-5
  weight_decay_f: 0.01
  max_epoch: 1500
  max_epoch_f: 300
  encoder: gat
  activation: prelu
  in_drop: 0.4
  attn_drop: 0
  linear_prob: True
  optimizer: adamw
  scheduler: True
  pred_hid: 512
  drop_edge_rate_1: 0.5
  drop_edge_rate_2: 0.5
  drop_feature_rate_1: 0.5
  drop_feature_rate_2: 0.5
pubmed:
  lr: 0.001
  lr_f: 0.01
  num_hidden: 1024
  num_heads: 4
  num_layers: 2
  weight_decay: 1e-5
  weight_decay_f: 1e-4
  max_epoch: 1200
  max_epoch_f: 300
  encoder: gat
  activation: prelu
  in_drop: 0.4
  attn_drop: 0
  linear_prob: True
  optimizer: adamw
  scheduler: True
  pred_hid: 512
  drop_edge_rate_1: 0.5
  drop_edge_rate_2: 0.5
  drop_feature_rate_1: 0.5
  drop_feature_rate_2: 0.5
ogbn-arxiv:
  lr: 0.001
  lr_f: 0.01
  num_hidden: 1024
  num_heads: 4
  num_layers: 4
  weight_decay: 1e-5
  weight_decay_f: 1e-4
  max_epoch: 60
  max_epoch_f: 1000
  encoder: gat
  activation: prelu
  in_drop: 0.4
  attn_drop: 0
  linear_prob: True
  optimizer: adamw
  scheduler: True
  pred_hid: 512
  drop_edge_rate_1: 0.5
  drop_edge_rate_2: 0.5
  drop_feature_rate_1: 0.5
  drop_feature_rate_2: 0.5
  batch_size: 256
  batch_size_f: 256
  residual: True
  norm: layernorm
ogbn-products:
  lr: 0.001
  lr_f: 0.01
  num_hidden: 1024
  num_heads: 4
  num_layers: 4
  weight_decay: 1e-5
  weight_decay_f: 1e-4
  max_epoch: 20
  max_epoch_f: 1000
  encoder: gat
  activation: prelu
  in_drop: 0.4
  attn_drop: 0
  linear_prob: True
  optimizer: adamw
  scheduler: True
  pred_hid: 512
  drop_edge_rate_1: 0.5
  drop_edge_rate_2: 0.5
  drop_feature_rate_1: 0.5
  drop_feature_rate_2: 0.5
  batch_size: 64
  batch_size_f: 256
  residual: True
  norm: layernorm
ogbn-papers100M:
  lr: 0.001
  lr_f: 0.01
  num_hidden: 1024
  num_heads: 4
  num_layers: 4
  weight_decay: 1e-5
  weight_decay_f: 1e-4
  max_epoch: 10
  max_epoch_f: 1000
  encoder: gat
  activation: prelu
  in_drop: 0.4
  attn_drop: 0
  linear_prob: True
  optimizer: adamw
  scheduler: True
  pred_hid: 512
  drop_edge_rate_1: 0.5
  drop_edge_rate_2: 0.5
  drop_feature_rate_1: 0.5
  drop_feature_rate_2: 0.5
  batch_size: 512
  batch_size_f: 256
  residual: True
  norm: layernorm