cora:
  lr: 0.001
  lr_f: 0.01
  num_hidden: 512
  num_heads: 4
  num_layers: 2
  weight_decay: 0
  weight_decay_f: 1e-4
  max_epoch: 100
  max_epoch_f: 2000
  encoder: gcn
  activation: prelu
  in_drop: 0
  attn_drop: 0
  linear_prob: True
  optimizer: adam
  scheduler: True
  dfr: 0.1
  der: 0.4
  lambd: 1e-3
citeseer:
  lr: 0.001
  lr_f: 0.01
  num_hidden: 512
  num_heads: 4
  num_layers: 1
  weight_decay: 0
  weight_decay_f: 1e-2
  max_epoch: 20
  max_epoch_f: 2000
  encoder: gcn
  activation: prelu
  in_drop: 0
  attn_drop: 0
  linear_prob: True
  optimizer: adam
  scheduler: True
  dfr: 0
  der: 0.4
  lambd: 5e-4
pubmed:
  lr: 0.001
  lr_f: 0.01
  num_hidden: 512
  num_heads: 4
  num_layers: 2
  weight_decay: 0
  weight_decay_f: 1e-4
  max_epoch: 80
  max_epoch_f: 2000
  encoder: gcn
  activation: prelu
  in_drop: 0
  attn_drop: 0
  linear_prob: True
  optimizer: adam
  scheduler: True
  dfr: 0.3
  der: 0.5
  lambd: 1e-3
ogbn-arxiv:
  lr: 0.0025
  lr_f: 0.005
  num_hidden: 1024
  num_heads: 8
  weight_decay: 0.06
  weight_decay_f: 1e-4
  max_epoch: 60
  max_epoch_f: 1000
  batch_size: 256
  batch_size_f: 512
  num_layers: 4
  encoder: gat
  activation: prelu
  attn_drop: 0.1
  linear_prob: True
  in_drop: 0.2
  optimizer: adamw
  scheduler: True
  residual: True
  norm: layernorm
  dfr: 0.5
  der: 0.5
  lambd: 1e-2
ogbn-products:
  lr: 0.002
  lr_f: 0.001
  num_hidden: 1024
  num_heads: 4
  num_layers: 4
  weight_decay: 0.04
  weight_decay_f: 0
  max_epoch: 20
  max_epoch_f: 1000
  batch_size: 256
  batch_size_f: 512
  encoder: gat
  activation: prelu
  attn_drop: 0.2
  linear_prob: True
  in_drop: 0.2
  optimizer: adamw
  scheduler: True
  residual: True
  norm: layernorm
  cluster_gcn_batch_size: 1
  cluster_gcn_num_parts: 50000
  dfr: 0.5
  der: 0.5
  lambd: 1e-2
ogbn-papers100M:
  lr: 0.002
  lr_f: 0.001
  num_hidden: 1024
  num_heads: 4
  num_layers: 4
  weight_decay: 0.04
  weight_decay_f: 0
  max_epoch: 20
  max_epoch_f: 1000
  batch_size: 512
  batch_size_f: 512
  encoder: gat
  activation: prelu
  attn_drop: 0.2
  linear_prob: True
  in_drop: 0.2
  optimizer: adamw
  scheduler: True
  residual: True
  norm: layernorm
  cluster_gcn_batch_size: 1
  cluster_gcn_num_parts: 50000
  dfr: 0.5
  der: 0.5
  lambd: 1e-2