cora:
  lr: 0.001
  lr_f: 0.05
  num_hidden: 512
  num_heads: 4
  num_layers: 1
  weight_decay: 0
  weight_decay_f: 0
  max_epoch: 500
  max_epoch_f: 300
  encoder: gcn
  activation: prelu
  in_drop: 0.4
  attn_drop: 0.1
  linear_prob: True
  optimizer: adamw
  scheduler: True
  drop_feat: 0
  num_proj_layer: 1
citeseer:
  lr: 0.001
  lr_f: 0.05
  num_hidden: 512
  num_heads: 4
  num_layers: 1
  weight_decay: 0
  weight_decay_f: 0
  max_epoch: 500
  max_epoch_f: 300
  encoder: gcn
  activation: prelu
  in_drop: 0.4
  attn_drop: 0.1
  linear_prob: True
  optimizer: adamw
  scheduler: True
  drop_feat: 0.1
  num_proj_layer: 1
pubmed:
  lr: 0.001
  lr_f: 0.05
  num_hidden: 512
  num_heads: 4
  num_layers: 1
  weight_decay: 0
  weight_decay_f: 0
  max_epoch: 500
  max_epoch_f: 300
  encoder: gcn
  activation: prelu
  in_drop: 0.4
  attn_drop: 0.1
  linear_prob: True
  optimizer: adamw
  scheduler: True
  drop_feat: 0.1
  num_proj_layer: 1
ogbn-arxiv:
  lr: 0.001
  lr_f: 0.05
  num_hidden: 512
  num_heads: 4
  num_layers: 1
  weight_decay: 0
  weight_decay_f: 0
  max_epoch: 20
  max_epoch_f: 1000
  encoder: gcn
  activation: prelu
  in_drop: 0.4
  attn_drop: 0.1
  linear_prob: True
  optimizer: adamw
  scheduler: True
  drop_feat: 0.1
  num_proj_layer: 1
ogbn-products:
  lr: 0.001
  lr_f: 0.05
  num_hidden: 512
  num_heads: 4
  num_layers: 1
  weight_decay: 0
  weight_decay_f: 0
  max_epoch: 20
  max_epoch_f: 1000
  encoder: gcn
  activation: prelu
  in_drop: 0.4
  attn_drop: 0.1
  linear_prob: True
  optimizer: adamw
  scheduler: True
  drop_feat: 0.1
  num_proj_layer: 1
ogbn-papers100M:
  lr: 0.001
  lr_f: 0.05
  num_hidden: 512
  num_heads: 4
  num_layers: 1
  weight_decay: 0
  weight_decay_f: 0
  max_epoch: 20
  max_epoch_f: 1000
  encoder: gcn
  activation: prelu
  in_drop: 0.4
  attn_drop: 0.1
  linear_prob: True
  optimizer: adamw
  scheduler: True
  drop_feat: 0.1
  num_proj_layer: 1