cora:
  lr: 0.001
  lr_f: 0.01
  num_hidden: 512
  num_heads: 4
  num_layers: 2
  weight_decay: 1e-5
  weight_decay_f: 1e-4
  max_epoch: 1500
  max_epoch_f: 300
  encoder: gcn
  activation: relu
  in_drop: 0.6
  attn_drop: 0.1
  linear_prob: True
  optimizer: adam
  scheduler: False
  num_proj_hidden: 512
  drop_edge_rate_1: 0.5
  drop_edge_rate_2: 0.5
  drop_feature_rate_1: 0.5
  drop_feature_rate_2: 0.5
  tau: 0.4
citeseer:
  lr: 0.001
  lr_f: 0.01
  num_hidden: 256
  num_heads: 4
  num_layers: 2
  weight_decay: 1e-5
  weight_decay_f: 1e-4
  max_epoch: 200
  max_epoch_f: 300
  encoder: gat
  activation: prelu
  in_drop: 0
  attn_drop: 0
  linear_prob: True
  optimizer: adam
  scheduler: False
  num_proj_hidden: 256
  drop_edge_rate_1: 0.2
  drop_edge_rate_2: 0
  drop_feature_rate_1: 0.3
  drop_feature_rate_2: 0.2
  tau: 0.9
pubmed:
  lr: 0.001
  lr_f: 0.01
  num_hidden: 1024
  num_heads: 4
  num_layers: 2
  weight_decay: 1e-5
  weight_decay_f: 1e-4
  max_epoch: 1200
  max_epoch_f: 300
  encoder: gcn
  activation: relu
  in_drop: 0.5
  attn_drop: 0.1
  linear_prob: True
  optimizer: adam
  scheduler: False
  num_proj_hidden: 512
  drop_edge_rate_1: 0.4
  drop_edge_rate_2: 0.1
  drop_feature_rate_1: 0.0
  drop_feature_rate_2: 0.2
  tau: 0.7
ogbn-arxiv:
  lr: 0.0025
  lr_f: 0.005
  num_hidden: 1024
  num_heads: 8
  weight_decay: 0.06
  weight_decay_f: 1e-4
  max_epoch: 60
  max_epoch_f: 1000
  batch_size: 512
  batch_size_f: 512
  num_layers: 4
  encoder: gat
  activation: prelu
  attn_drop: 0.1
  linear_prob: True
  in_drop: 0.2
  optimizer: adamw
  scheduler: True
  residual: True
  norm: layernorm
  num_proj_hidden: 512
  drop_edge_rate_1: 0.5
  drop_edge_rate_2: 0.5
  drop_feature_rate_1: 0.5
  drop_feature_rate_2: 0.5
  tau: 0.5
ogbn-products:
  lr: 0.002
  lr_f: 0.001
  num_hidden: 1024
  num_heads: 4
  num_layers: 4
  weight_decay: 0.04
  weight_decay_f: 0
  max_epoch: 20
  max_epoch_f: 1000
  batch_size: 512
  batch_size_f: 512
  encoder: gat
  activation: prelu
  attn_drop: 0.2
  linear_prob: True
  in_drop: 0.2
  optimizer: adamw
  scheduler: True
  residual: True
  norm: layernorm
  cluster_gcn_batch_size: 1
  cluster_gcn_num_parts: 50000
  num_proj_hidden: 512
  drop_edge_rate_1: 0.5
  drop_edge_rate_2: 0.5
  drop_feature_rate_1: 0.5
  drop_feature_rate_2: 0.5
  tau: 0.5
ogbn-papers100M:
  lr: 0.002
  lr_f: 0.001
  num_hidden: 1024
  num_heads: 4
  num_layers: 4
  weight_decay: 0.04
  weight_decay_f: 0
  max_epoch: 20
  max_epoch_f: 1000
  batch_size: 512
  batch_size_f: 512
  encoder: gat
  activation: prelu
  attn_drop: 0.2
  linear_prob: True
  in_drop: 0.2
  optimizer: adamw
  scheduler: True
  residual: True
  norm: layernorm
  cluster_gcn_batch_size: 1
  cluster_gcn_num_parts: 50000
  num_proj_hidden: 512
  drop_edge_rate_1: 0.5
  drop_edge_rate_2: 0.5
  drop_feature_rate_1: 0.5
  drop_feature_rate_2: 0.5
  tau: 0.5